### ISSUE TITLE
Pre Selected Options are not displaying

### ISSUE THREAD

**Issue by pandeyamit** [vova07/yii2-select2-widget#2]
It is not mentioned anywhere how to display the preselected options. 
Is there any way to display preselected option.

**Comment by vova07** [comment]
Hi @pandeyamit, 
Can you give some code example of your widget settings?
If your model `attribute` is a single value, or an array, the widget my set the values by default.

**Comment by pandeyamit** [comment]
Hello, 
thx for quick reply. Here is my code example:

<p> Select Company
        <?php
        $dataList = ArrayHelper::map($company, 'id', 'name');
        echo $form->field($model, 'company_id')->widget(Widget::className(), [
            'options' => [
                'multiple' => true,
                'placeholder' => 'Choose Companies',
            ],
            'settings' => [
                'width' => '50%',
            ],
            'items' => $dataList,
            'attribute' => 'name',

        ]);
        ?>
    </p>

I want to show the selected companies of the user. I have a table user_companies having fields
id, user_id, company_id.
e.g one user has many companies association is used.

**Comment by vova07** [comment]
You need to set `company_id` attribute like an array with selected `id` of user companies.
Short instruction:
- If `company_id` is the real user's model attribute, or it's used in another places in your code, add a new attribute for this case, for example `companyArray`.
```php
// User.php (user model)
protected $_companyArray;
``` 
- Set the needed value for your `companyArray` attribute in the same model.
```php
// User.php (user model)

// Setter for $_companyArray
public function setCompanyArray($value)
{
    $this->_companyArray = $value;
}

// Getter for $_companyArray
public function getCompanyArray()
{
    // Note $this->companies is the has many relation that must be specified in "User" model 
    if ($this->_companyArray === null && !empty($this->companies)) {
        $this->_companyArray = [];
        foreach ($this->companies as $company) {
            $this->_companyArray[] = $company->id;       
        }
    }
    return $this->_companyArray;
}
```
- Use new attribute in your `_form` view. `... field($model, 'companyArray') ...`
- Profit!

**Comment by pandeyamit** [comment]
Hello,

Thanks for your answer, I will try to do by this way.

On Thu, Jan 15, 2015 at 3:08 PM, Vasile C. <notifications@github.com> wrote:

> You need to set company_id attribute like an array with selected id of
> user companies.
> Short instruction:
>
>    - If company_id is the real user's model attribute, or it's used in
>    another places in your code, add a new attribute for this case, for example
>    companyArray.
>
> // User.php (user model)protected $_companyArray;
>
>
>    - Set the needed value for your companyArray attribute in the same
>    model.
>
> // User.php (user model)// Setter for $_companyArraypublic function setCompanyArray($value){    $this->_companyArray = $value;}// Getter for $_companyArraypublic function getCompanyArray(){    // Note $this->companies is the has many relation that must be specified in "User" model     if ($this->_companyArray === null && !empty($this->companies)) {        $this->_companyArray = [];        foreach ($this->companies as $company) {            $this->_companyArray[] = $company->id;               }    }    return $this->_companyArray;}
>
>
>    - Use new attribute in your _form view. ... field($model,
>    'companyArray') ...
>    - Profit!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vova07/yii2-select2-widget/issues/2#issuecomment-70060856>
> .
>



-- 
Thanks.

Best Regards !!

Amit Pandey
Sr. Software Engineer.
Soarlogic Information Technology Pvt. Ltd.

Mobile :- 9012474075
Mail to:- amit.pandey@soarlogic.com
